package depgraph.ImageRenderer;

/**
 * Relatively simple class. It takes a format and output file name and and
 * creates and runs a process based off a run string generated by this class
 * (see createRunString).
 */
public class ImageRenderer {

	/**
	 * Runtime instace. Used to execute programs.
	 */
	private Runtime runtime;

	/**
	 * Used to keep track of the command line process until it has finished
	 * executing.
	 */
	private Process process;

	/**
	 * No-arg constructor. Initializes the runtime instance.
	 */
	public ImageRenderer() {
		runtime = Runtime.getRuntime();
	}

	/**
	 * Renders the graph image by creating a dot run string. Specifies the type and
	 * output file name.
	 *
	 * @param format   Format the image should be generated as.
	 * @param fileName Name of the output file.
	 */
	public void renderImage(String format, String fileName) {
		try {
			process = runtime.exec(createRunString(format, fileName));
			process.waitFor();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * Creates a run string from the format of the image and nmae of the output
	 * file.
	 *
	 * @param format   Image format.
	 * @param fileName Output file name.
	 * @return Valid run string to create a process from.
	 */
	private String createRunString(String format, String fileName) {
		return String.format("dot -T%s -o %s out.dot", format, fileName);
	}
}
